apiVersion: v2
name: kube-httpcache
description: Varnish on Kubernetes Helm Chart
version: 0.8.1
appVersion: v0.8.1
home: https://varnish-cache.org
icon: https://varnish-cache.org/_static/varnish-bunny.png
sources:
  - https://github.com/mittwald/kube-httpcache
