{{- if not .Values.useStatefulset.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-httpcache.fullname" . }}
  labels:
    {{- include "kube-httpcache.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "kube-httpcache.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "kube-httpcache.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-httpcache.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- with .Values.initContainers }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          args:
          - -admin-addr=0.0.0.0
          - -admin-port=6083
          - -signaller-enable
          - -signaller-port=8090
          - -frontend-port={{ .Values.service.target }}
          {{- if .Values.cache.frontendWatch }}
          - -frontend-watch
          {{- else }}
          - -frontend-watch=false
          {{- end }}
          - -frontend-namespace={{ "$(NAMESPACE)" }}
          - -frontend-service={{ .Values.cache.frontendService | default (include "kube-httpcache.fullname" .) }}
          {{- if .Values.cache.backendWatch }}
          - -backend-watch
          {{- else }}
          - -backend-watch=false
          {{- end }}
          - -backend-service={{ tpl .Values.cache.backendService . }}
          - -backend-namespace={{ .Values.cache.backendServiceNamespace | default "$(NAMESPACE)" }}
          - -varnish-secret-file=/etc/varnish/k8s-secret/secret
          - -varnish-vcl-template=/etc/varnish/tmpl/default.vcl.tmpl
          - -varnish-storage={{ .Values.cache.varnishStorage }},{{ .Values.cache.storageSize }}
          {{- if .Values.configmap.enabled }}
          {{/* When loading the VCL template from a ConfigMap, inotify is not reliable */}}
          - -varnish-vcl-template-poll
          {{- end }}
          {{- if .Values.cache.varnishTransientStorage }}
          - -varnish-transient-storage={{ .Values.cache.varnishTransientStorage }},{{ .Values.cache.transientStorageSize }}
          {{- end }}
          {{- if .Values.cacheExtraArgs }}
            {{- with .Values.cacheExtraArgs }}
            {{- tpl . $ | trim | nindent 10 }}
            {{- end }}
          {{- end }}
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- with .Values.extraEnvVars }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- if .Values.extraEnvFromConfig }}
          envFrom:
          {{- toYaml .Values.extraEnvFromConfig | nindent 12 }}
          {{- end }}
          {{- if .Values.lifecycle }}
          lifecycle:
            {{- toYaml .Values.lifecycle | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: template
            mountPath: /etc/varnish/tmpl
          - name: secret
            mountPath: /etc/varnish/k8s-secret
          - name: var
            mountPath: /var/lib/varnish
          {{- if .Values.extraMounts }}
            {{- toYaml .Values.extraMounts | nindent 10 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
        {{- if .Values.exporter.enabled }}
        - name: exporter
          securityContext:
            {{- toYaml .Values.exporter.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /exporter/prometheus_varnish_exporter
          args:
          - -no-exit
          env:
          - name: VSM_NOPID
            value: "1"
          ports:
          - name: metrics
            containerPort: 9131
          volumeMounts:
          - name: var
            mountPath: /var/lib/varnish
          {{- if .Values.exporter.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.exporter.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.exporter.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.exporter.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.exporter.resources }}
          resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if .Values.extraContainers }}
          {{- toYaml .Values.extraContainers | nindent 8 }}
        {{- end }}
      volumes:
      {{- if .Values.configmap.enabled }}
      - name: template
        configMap:
          name: {{ include "kube-httpcache.fullname" . }}
      {{- end }}
      - name: secret
        secret:
          secretName: {{ .Values.cache.existingSecret | default (include "kube-httpcache.fullname" .) }}
      - name: var
        emptyDir: {}
      {{- if .Values.extraVolumes -}}
      {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
{{- end }}
